version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

networks:
  quiniela_network_local:
    name: quiniela_network_local
    driver: bridge
    ipam:
      driver: default

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: quiniela_local_django
    container_name: django
    depends_on:
      - postgres
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start
    networks:
      quiniela_network_local:
        aliases:
          - django

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: quiniela_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    networks:
      quiniela_network_local:
        aliases:
          - postgres

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      quiniela_network_local:
        aliases:
          - mailhog

  redis:
    image: redis:5.0
    container_name: redis
    networks:
      quiniela_network_local:
        aliases:
          - redis

  celeryworker:
    <<: *django
    image: quiniela_local_celeryworker
    container_name: celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker
    networks:
      quiniela_network_local:
        aliases:
          - celeryworker

  celerybeat:
    <<: *django
    image: quiniela_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
    networks:
      quiniela_network_local:
        aliases:
          - celerybeat

  flower:
    <<: *django
    image: quiniela_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
    networks:
      quiniela_network_local:
        aliases:
          - flower
  
  front:
    build:
      context: .
      dockerfile: compose/local/node/Dockerfile
    image: quiniela_local_front
    container_name: quiniela_local_front
    depends_on:
      - django
    volumes:
      - "./quiniela-front/:/app"
      - "/app/node_modules"
    ports:
      - "3000:3000"
    command: /bin/sh -c "yarn serve"
    networks:
      quiniela_network_local:
        aliases:
          - front
