# Generated by Django 3.1.7 on 2021-04-18 16:52

from django.db import migrations

def create_default_user_profile_roles(apps, schema_editor):
    UserProfileRole = apps.get_model("users", "UserProfileRole")

    UserProfileRole.objects.create(role="admin")
    UserProfileRole.objects.create(role="manager")
    UserProfileRole.objects.create(role="player")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210401_1115'),
    ]

    operations = [
        migrations.RunPython(create_default_user_profile_roles),
    ]
