# Generated by Django 3.1.7 on 2021-04-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        ('users', '0003_create_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='leagues',
            field=models.ManyToManyField(blank=True, null=True, to='league.League', verbose_name='Ligas'),
        ),
    ]
