# Generated by Django 3.1.7 on 2021-04-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_leagues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='leagues',
        ),
    ]
