# Generated by Django 3.1.7 on 2021-09-15 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_leagues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Users Profiles'},
        ),
        migrations.AlterModelOptions(
            name='userprofilerole',
            options={'verbose_name': 'role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Names'),
        ),
        migrations.AlterField(
            model_name='user',
            name='second_last_name',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='Second last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to='users.userprofilerole', verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofilerole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='userprofilerole',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modify Date'),
        ),
        migrations.AlterField(
            model_name='userprofilerole',
            name='role',
            field=models.CharField(max_length=24, primary_key=True, serialize=False, unique=True, verbose_name='Role'),
        ),
    ]
