# Generated by Django 3.1.7 on 2021-04-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='enroll_code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Codigo Inscripción'),
        ),
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Publica'),
        ),
    ]
