# Generated by Django 3.1.7 on 2021-09-15 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league', '0003_userprofileleagueenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofileleagueenrollment',
            options={'verbose_name': 'League Enrollment', 'verbose_name_plural': 'Leagues Enrollments'},
        ),
        migrations.AddField(
            model_name='userprofileleagueenrollment',
            name='team_name',
            field=models.CharField(default='otro', max_length=120, verbose_name="Team's name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='league',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='league_league_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='enroll_code',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Enrollment Code'),
        ),
        migrations.AlterField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Public'),
        ),
        migrations.AlterField(
            model_name='league',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date'),
        ),
        migrations.AlterField(
            model_name='league',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_league_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=120, verbose_name="League's name"),
        ),
        migrations.AlterField(
            model_name='userprofileleagueenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='userprofileleagueenrollment',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='league_userprofileleagueenrollment_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofileleagueenrollment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='userprofileleagueenrollment',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date'),
        ),
        migrations.AlterField(
            model_name='userprofileleagueenrollment',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='league_userprofileleagueenrollment_modified', to=settings.AUTH_USER_MODEL),
        ),
    ]
