# Generated by Django 3.1.7 on 2021-11-16 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NflTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date')),
                ('name', models.CharField(max_length=120, verbose_name='Teams')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('logo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='nfl_teams/logo/%Y/%m/%d/', verbose_name='Logo')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_nflteams_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_nflteams_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creation Date')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modify Date')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='games.nflteams', verbose_name='Away Team')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='games_games_created', to=settings.AUTH_USER_MODEL)),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='games.nflteams', verbose_name='Home Team')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games_games_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
