# Generated by Django 3.1.7 on 2021-11-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Game date'),
        ),
    ]
